### ISSUE TITLE
"without a file extension" -> also works for .coffee .json .md

### ISSUE THREAD

**Issue by forresto** [whomwah/qlstephen#28]
Thanks for this plugin!

My suggestion is to change the wording in the readme, since it works for all of these text file extensions that don't work with QuickLook out of the box.

**Comment by tsdorsey** [comment]
TL;DR: qlstephen is not greedy about matching file types so any QL plugin that specifies a specific file type will be chosen over qlstephen.

qlstephen uses the public.data UTI which is [described by Apple](https://developer.apple.com/library/ios/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html) as the "Base physical type for byte streams (flat files, pasteboard data, and so on)". Because of this anything that is more specific will be chosen over it. This allows qlstephen to play nice with other QL plugins.
