### ISSUE TITLE
Tries to render Adobe InDesign files

### ISSUE THREAD

**Issue by tweh** [whomwah/qlstephen#32]
Thanks for the nice plug-in, but it tries to render InDesign files which it should, because this

![bildschirmfoto 2014-06-19 um 00 59 39](https://cloud.githubusercontent.com/assets/3011538/3321758/45eabac4-f73c-11e3-8521-80f7f39d0919.png)

isn’t that helpful … theres no rendering for these files they show as an icon, but I’d prefer the icon against the messy text … is it possible to prevent you plugin from redering `.indd` files?

**Comment by kylamedina** [comment]
@tweh do you have a link to that plugin?

**Comment by tweh** [comment]
@kylamedina I guess it is from here: http://www.jenny-hofer.de/sternchens-senf/archive/2008-12-14/fertig_inddqlgenerator ([direct download link](http://www.jenny-hofer.de/software/inddQLgenerator/inddQLgenerator.dmg))

**Comment by tomfado** [comment]
Hi, I saw this closed issue because of the recent question from kylamedina. If you don't mind I will reopen this issue as a feature request to explore a bit more how to best handle this. One would think that the Finder Quicklook feature should at least, if not able to preview due to lack of feature in a specific application, tell the user about this: "an app exist that support this format but does not provide a Quicklook view plugin".

Thank you for bringing this to the table :-)

**Comment by frankrolf** [comment]
Thanks for re-opening. I am experiencing the same problem with `.indd` files.

**Comment by tsdorsey** [comment]
#37 Adds a new feature by @comawill that limits the preview to the first 100KB. This will speed up rendering of large files. This is not a complete solution but does remove some of the pain.

**Comment by tsdorsey** [comment]
Consolidated to #87
