### ISSUE TITLE
QLStephen + iCloud Drive

### ISSUE THREAD

**Issue by yegortimoshenko** [whomwah/qlstephen#63]
iCloud Drive uploads thumbnails (including those generated by QLStephen) to the cloud. That means if you store large Git repos, you end up with iCloud Drive (more precisely, `revisiond` and `bird`) constantly trying to upload 15-20 GB worth of thumbnails... My Mac was going crazy for several months and I've finally found the reason. Beware.

![Disk Inventory X](https://s3.amazonaws.com/yegortimoshenko/Screen+Shot+2017-06-29+at+2.06.11+AM.png)

Thumbnail sample:

![thumbnail sample](https://s3.amazonaws.com/yegortimoshenko/qlstephen-thumbnail-fiasco-sample.png)

```
$ pwd
/Users/yegortimoshenko/Library/Application Support/CloudDocs/session/u
$ find -name thumbnail | wc -l
165546
```

**Comment by tsdorsey** [comment]
Wow! Just Wow! That graph is terrifying.
Thank you for finding this.

Not sure there is anything to be done on the plugin side. I'll have to read through the updated quicklook API docs to see if there is flag that can be set to prevent this. I suspect not, QLStephen is uncommon in that it registers a very low level file type (anything text based) so that any text file not claimed by another quick look plugin will fall back to using it. The downside appears to be that when iCloud drive's new feature (sync quicklook thumbnails) does it's search to see which files have registered renderers the answer comes back with many more files than Apple expected.

**Comment by yegortimoshenko** [comment]
I've switched to Linux, so I'm closing the issue. Feel free to reopen it if you want to do something about it.
