### ISSUE TITLE
> I can QL RELEASE-NOTES but not catalina.out

### ISSUE THREAD

**Issue by ballo** [whomwah/qlstephen#92]
> There is a process called `qlmanage` which handles deciding which plugin to use for a given file.

That's not an answer to my question. I'm asking if there is a running process which loads the bundle, not for a utility program which determines permissions.

**Comment by tsdorsey** [comment]
I don't know the answer to that question. 

`qlmanage` is a development utility that manages the quicklook plugins. It handles registering the bundles with the os (or whatever process might exist that you're asking about). It also handles clearing the cache of previews.

[Apple Documentation](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/Quicklook_Programming_Guide/Articles/QLDebugTest.html) points to using qlmanage to reload and flush the cache of quicklook plugins during development. How they implement the loading of bundles is up to them. It would be interesting to know, but would not really inform the features/fixes of `qlstsephen` going forward.

All that being said, the issues section of this repository isn't really the correct place to figure it out because it's not an issue for this plugin. [I think "ask different" would be a better place.](https://apple.stackexchange.com/search?q=quicklook+process)
